config/routes.rb
Rails.application.routes.draw do
  #get 'users/new'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects, only: [:create, :destroy] 
  resources :tasks
  
  root  'users#show'
   
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks
	belongs_to :user
	validates :name, presence: true, length: { maximum: 100 }
	validates :user_id, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
	validates :project_id, presence: true
	validates :name, presence: true, length: { maximum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :projects
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX  = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
	                  uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }

   def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
     include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user,   only: :destroy

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = "Project created!"
      redirect_to root_url
    else
       redirect_to root_url
    end  	
  end

  def destroy
  	@project.destroy
  	redirect_to root_url
  end

  private

    def project_params
      params.require(:project).permit(:name)
    end

    def correct_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to root_url if @project.nil?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	   user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :signed_in_user

  def create
  	#if @current_project != nil
  	current_project = Project.find(params[:project_id])
    @task = current_project.tasks.build(task_params)
    if @task.save
    	@task.status = 'process'
      flash[:success] = "Task created! "+@task.name
      redirect_to root_url
    else
      redirect_to root_url
    end
   # else
   #   redirect_to root_url
   # end
  end
	

  def destroy
   @task = Task.find(params[:id])
    if @task.present?
      @task.destroy
    end
    redirect_to root_url
  end

  private

    def task_params
      params.require(:task).permit(:name)
    end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	if signed_in? 
        @user=current_user 
        @projects = @user.projects
        @project = current_user.projects.build if signed_in?
        @tasks = @project.tasks
        @task = @project.tasks.build if signed_in?        
       #@user = User.find(params[:id])
    end
  end

  def new
    @user = User.new  	
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
    	    sign_in @user
    	    flash[:success] = "Welcome to the TODO App!"
            redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  

  def edit_status(task)
    if task.status == "done" 
      task.status = nil
      flash[:success] = "Task created! "+task.name
    else
      task.status = "done"
      flash[:success] = "Task created! "+task.name+task.status
   
    end   
    return '#'
  end
   def current_user=(user)
    @current_user = user
  end

  def current_project=(project)
    @current_project = project
  end  

  def current_project
     @current_project ||= nil
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "todo app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right navbar-nav">

          <% if signed_in? %>
              <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 <%= @user.name %>   <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">

                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", signup_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>            
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sign-in_show.html.erb
 <div class="center hero-unit">


   <div class="span8 ">
    <% if @user.projects.count != 0 %>
      
      <ul class="">
        <%= render @projects %>
      </ul>
   
    <% end %>
  </div>


   
     <section>
        <%= render 'shared/project_form' %>
      </section>
 </div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', "data-turbolinks-track"=> "reload" %> 
  

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>  
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
     
    </div>
  </body>
</html>

app/views/projects/_11111projects.html.erb
<li>
  <span class="name"><%= project.name %></span>

</li>

app/views/projects/_project.html.erb
<% if project.name != nil %>
<div class ="projects">
<li class="name">
  <div  class="project-name"><%= project.name %></div>

  <% if current_user?(project.user) %>
    <%= link_to image_tag("trash.png", alt:"delete"), project,method: :delete, class: " right",
                                     data: { confirm: "You sure?" },
                                     title: project.name %>
  <% end %>
</li>


     <section>


<%= form_for @task, html: { class: " form-inline task-form" } do |f| %>
    <%= hidden_field_tag(:project_id, project.id) %>
    <%= f.text_field :name, class: "task-text-field", placeholder: "New task..." %>
   <%= f.submit "Add task", class: "btn task-btn " %>
<% end %>



      </section>

   <div class="">
    <% if project.tasks.any? %>
      <ul >
        <%= render project.tasks %>
      </ul>
   
    <% end %>
  </div>


 </div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_projects.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_project_form.html.erb
<%= form_for @project , html: { class: " form-inline project-form " }  do |f| %>
 <%= render 'shared/error_messages_projects', object: f.object %>

 


  <%= f.text_field :name, html: { class: " " }, placeholder: "Project name" %>

  <%= f.submit "Add project", class: "btn  btn-primary " %>

<% end %>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :name, placeholder: "Compose new task..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-mikro btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<li class="tasks" >
<div class="task-name task-1"><%= task.name %></div>
 
<div class="task-1 task-nav">


    <div class="task-1 ">
     <%= link_to image_tag("trash.png", alt:"delete"), task, method: :delete,
                                         data: { confirm: "You sure?" },
                                         title: task.name %>
    </div>
</div>
</li>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>

    <div>
       <% if signed_in? %>
            <%= render 'layouts/sign-in_show' %>   
        <% else %>
          <div class="center hero-unit">        
             <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
          </div>   
        <% end %>  
     </div>   
    </section>
  </aside>
</div>